# Generated by Django 4.1.6 on 2023-02-02 02:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FantasyLeague",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("start_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FantasyTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.fantasyleague",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("QB", "QB"),
                            ("WR", "WR"),
                            ("RB", "RB"),
                            ("TE", "TE"),
                            ("IDP", "IDP"),
                        ],
                        default="QB",
                        max_length=3,
                    ),
                ),
                ("height", models.PositiveSmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField()),
                ("college", models.CharField(max_length=128, null=True)),
                ("nfl_draft_pick", models.PositiveSmallIntegerField()),
                ("birthdate", models.DateTimeField()),
                (
                    "fantasy_teams",
                    models.ManyToManyField(
                        related_name="roster", to="catalog.fantasyteam"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster",
                        to="catalog.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="fantasyleague",
            constraint=models.CheckConstraint(
                check=models.Q(("start_year__gte", 2000), ("start_year__lte", 2100)),
                name="Start year is between 2000 and 2100",
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyteam",
            constraint=models.UniqueConstraint(
                fields=("name", "league"), name="unique_fantasy_team_name_in_league"
            ),
        ),
    ]
